version: "3.9"
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    volumes:
      - static_volume:/data/db
    expose:
      - 27017
    ports:
      - "0.0.0.0:27017:27017"

volumes:
  static_volume:
