import mongoose from "mongoose";

const HeadphonesSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  name: String,
  Brand: String,
  Model: String,
  Title: String,
  Warranty: String,
  BoxContents: String,
  Type: String,
  Design: String,
  OpenOrClosedBack: String,
  Fit: String,
  Impedance: String,
  Sensitivity: String,
  MaxFrequencyResponse: String,
  MinFrequencyResponse: String,
  MaxPowerInput: String,
  DriverType: String,
  MagnetMaterial: String,
  Weight: String,
  FoldableDesign: String,
  Colour: String,
  DriverSize: String,
  NoiseCancellation: String,
  NoiseReduction: String,
  LEDHeadphones: String,
  CallControl: String,
  MusicControl: String,
  Connector: String,
  Range: String,
  Microphone: String,
  BatteryType: String,
  PlaybackTime: String,
  BatteryCapacity: String,
  StandbyTime: String,
  ChargingType: String,
  ChargingTime: String,
  CompatibleModels: String,
  variants: [
    {
      store: String,
      price: String,
      store_link: String,
    },
  ],
  images: [String],
  ExpertScore: String,
});

export const Headphones = mongoose.model("headphones", HeadphonesSchema);
