import mongoose from "mongoose";

const laptopSchema = new mongoose.Schema({
  name: String,
  Brand: String,
  Thickness: String,
  Model: String,
  Dimensions: String,
  Weight: String,
  Colors: String,
  "Operating System": String,
  "Display Size": String,
  "Display Resolution": String,
  "Pixel Density": String,
  "Display Features": String,
  "Display Touchscreen": String,
  "Refresh Rate": String,
  "Aspect Ratio": String,
  Brightness: String,
  Processor: String,
  "Clock-speed": String,
  "Number of Cores": String,
  "Graphic Processor": String,
  "Graphics Memory": String,
  Capacity: String,
  "RAM Type": String,
  "RAM Speed": String,
  "Memory Slots": String,
  "Expandable Memory": String,
  "Memory Layout": String,
  "SSD Capacity": String,
  "SSD Type": String,
  "Battery Cell": String,
  "Battery Type": String,
  "Power Supply": String,
  "Wireless LAN": String,
  "Wi-Fi Version": String,
  Bluetooth: String,
  "Bluetooth Version": String,
  "Thunderbolt Port": String,
  "Ethernet ports": String,
  "Headphone Jack": String,
  "Microphone Jack": String,
  "VGA Port": String,
  "Web-cam": String,
  "Video Recording": String,
  "Audio Solution": String,
  Speakers: String,
  "Sound Technologies": String,
  "In-built Microphone": String,
  "Microphone Type": String,
  "Pointing device": String,
  Keyboard: String,
  "Backlit Keyboard": String,
  Warranty: String,
  "Sales Package": String,
  variants: [
    {
      store: String,
      price: String,
      store_link: String,
    },
  ],
  images: [String],
  "Expert Score": String,
});

export const Laptops = mongoose.model("laptops", laptopSchema);
