import mongoose from "mongoose";

const MicrowaveOvenSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  name: String,
  Title: String,
  Brand: String,
  Model_No: String,
  Capacity: String,
  Control_Type: String,
  Display_Type: String,
  LED_Display: String,
  Oven_Depth: String,
  Oven_Height: String,
  Oven_Width: String,
  Type: String,
  Cavity_Material: String,
  Door_Material: String,
  Door_Opening_Mechanism: String,
  Turntable: String,
  Turntable_Diameter: String,
  Auto_Cook_Menu: String,
  Cooking_Completion_Indicator: String,
  Cooking_Mode: String,
  Defrost: String,
  Preheat: String,
  Steam_Cook: String,
  Child_Lock: String,
  Other_Convenience_Features: String,
  Safety_Features: String,
  Timer: String,
  Consumption_Convection: String,
  Consumption_Grill: String,
  Frequency: String,
  Power_Consumption: String,
  Power_Output: String,
  Voltage: String,
  Microwave_Frequency: String,
  Power_Levels: String,
  Covered_in_Warranty: String,
  Not_Covered_in_Warranty: String,
  Package_Contents: String,
  Warranty_Duration: String,
  Warranty_Type: String,
  variants: [
    {
      store: String,
      price: String,
      store_link: String,
    },
  ],
  images: [String],
  ExpertScore: String,
},{ collection: 'microwave_oven' });

export const MicrowaveOven = mongoose.model("microwave_oven", MicrowaveOvenSchema);
