import mongoose from "mongoose";
const SmartphoneSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  name: String,
  "Processor Chipset": String,
  RAM: String,
  "Rear Camera": String,
  "Internal Memory": String,
  "Screen Size": String,
  "Battery Capacity": String,
  Chipset: String,
  "No Of Cores": String,
  CPU: String,
  Architecture: String,
  Fabrication: String,
  "RAM Type": String,
  Graphics: String,
  Height: String,
  Width: String,
  Thickness: String,
  Weight: String,
  Colors: String,
  "Water Resistant": String,
  Ruggedness: String,
  "Screen Unlock": String,
  Resolution: String,
  "Aspect ratio": String,
  "Display Type": String,
  Size: String,
  "Bezel-less display": String,
  "Pixel Density": String,
  Protection: String,
  TouchScreen: String,
  "Color Reproduction": String,
  "Screen to body percentage": String,
  "Display Refresh Rate": String,
  "Touch Refresh Rate": String,
  "Rear camera setup": String,
  "Rear camera  (Primary)": String,
  "Rear camera  (Secondary)": String,
  "Rear camera  (Tertiary)": String,
  "Front camera setup": String,
  "Front camera  (Primary)": String,
  Sensor: String,
  Flash: String,
  "Digital zoom": String,
  "Video Resolution  (Rear)": String,
  "Video Resolution  (Front)": String,
  "Video Recording Features": String,
  "Optical Image Stabilization(OIS)": String,
  "Electric Image Stabilization (EIS)": String,
  "Camera Features": String,
  "Shooting Modes": String,
  Type: String,
  Capacity: String,
  Removable: String,
  "Fast Charging": String,
  "Charging speed": String,
  "Wireless Charging": String,
  "Memory type": String,
  "Expandable Memory": String,
  "Operating System": String,
  "Custom UI": String,
  "SIM Configuration": String,
  Network: String,
  "SIM1 Bands": String,
  "SIM2 Bands": String,
  "Voice over LTE(VoLTE)": String,
  "Wi-Fi": String,
  "Wi-fi features": String,
  USB: String,
  Bluetooth: String,
  "USB OTG Support": String,
  GPS: String,
  "NFC Chipset": String,
  Infrared: String,
  Speaker: String,
  "Speaker Features": String,
  "Audio Jack": String,
  "Video Player": String,
  "Fingerprint sensor": String,
  "Face Unlock": String,
  "Other Sensor": String,
  Overall: String,
  GPU: String,
  Memory: String,
  UX: String,
  "Single-core": String,
  "Multi-core": String,
  variants: [
    {
      store: String,
      price: String,
      store_link: String,
    },
  ],
  images: [String],
  "Expert Score": String,
});

export const Smartphone = mongoose.model("new_smartphones", SmartphoneSchema);
