import mongoose from "mongoose";

const RefrigeratorSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  name: String,
  Title: String,
  Brand: String,
  Capacity: String,
  CoolingTechnology: String,
  DefrostingTechnology: String,
  EnergyRating: String,
  ModelNo: String,
  RefrigeratorType: String,
  ActiveCarbonFilter: String,
  AntiBacteriaFilter: String,
  AirCirculation: String,
  ExpressFreezing: String,
  FreezerLocation: String,
  FreezerLamp: String,
  FreezerShelf: String,
  IceTray: String,
  IceCubeBox: String,
  IcemakerType: String,
  PowerSupply: String,
  HumidityController: String,
  MoistBalanceCrisper: String,
  Color: String,
  DoorFinish: String,
  DoorLock: String,
  Exterior: String,
  ExteriorDisplay: String,
  ExteriorDoorFinishing: String,
  ExteriorFinish: String,
  Handle: String,
  HandleDesign: String,
  HandleType: String,
  IceDispenser: String,
  InteriorsLamp: String,
  Lighting: String,
  ShelfBottle: String,
  TemperedGlass: String,
  WaterDispenser: String,
  Height: String,
  Width: String,
  Depth: String,
  TurboMode: String,
  CoolingModes: String,
  Warranty: String,
  PackageContents: String,
  CompressorWarranty: String,
  Refrigerant: String,
  StabilizerFreeOperation: String,
  TemperatureControl: String,
  variants: [
    {
      store: String,
      price: String,
      store_link: String,
    },
  ],
  images: [String],
  ExpertScore: String,
});

export const Refrigerators = mongoose.model("refrigerators", RefrigeratorSchema);
