import mongoose from "mongoose";
const TVSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  name: String,
  Brand: String,
  Model: String,
  Warranty: String,
  "Box Contents": String,
  Type: String,
  "Size(Diagonal)": String,
  Resolution: String,
  "Refresh Rate": String,
  "Contrast Ratio": String,
  "Aspect Ratio": String,
  "Horizontal Viewing Angles": String,
  "Vertical Viewing Angles": String,
  "3D TV": String,
  "Curved TV": String,
  "Ultra Slim TV": String,
  "Other Display Features": String,
  Colour: String,
  "Weight Without Stand": String,
  "Weight With Stand": String,
  "Dimensions With Stand(WxDxH)": String,
  "Dimensions Without Stand(WxDxH)": String,
  "Stand Colour": String,
  "Digital TV Reception Formats": String,
  "Video Formats Supported": String,
  "Image Formats Supported": String,
  Upscaling: String,
  "Other Video Features": String,
  "Sound Type": String,
  "Audio Formats Supported": String,
  "No. of Speakers": String,
  "Output per Speaker": String,
  "Total Speaker Output": String,
  "Speaker Frequency Range": String,
  "Other Smart Audio Features": String,
  "USB Ports": String,
  "USB Supports": String,
  "HDMI Ports": String,
  "Digital/Optical Audio Output Ports": String,
  "RF Input(Analog Coaxial) Ports": String,
  "Ethernet Sockets": String,
  "Smart TV": String,
  "Wifi Present": String,
  "Band Support": String,
  "Wifi-Direct Support": String,
  "Miracast/Screen Mirroring Support": String,
  Bluetooth: String,
  "Bluetooth Version": String,
  "Processor Type": String,
  "Inbuilt Apps": String,
  "Facebook and Social Media Integration": String,
  Games: String,
  "Voice Recognition": String,
  "Other Smart Features": String,
  "Cell Requirement": String,
  "Other Remote Features": String,
  "Voltage Requirement": String,
  "Frequency Requirement": String,
  "Power Consmption Standby": String,
  variants: [
    {
      store: String,
      price: String,
      store_link: String,
    },
  ],
  images: [String],
  "Expert Score": String,
});

export const TVs = mongoose.model("TVs", TVSchema);
