import mongoose from "mongoose";

const WashingMachineSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  name: String,
  Title: String,
  Brand: String,
  ModelNo: String,
  Capacity: String,
  Color: String,
  KeyFeatures: [String],
  Type: String,
  Control: String,
  WashModes: {
    Bedding: String,
    CleanTub: String,
    Cotton: String,
    DailyWash: String,
    Delicate: String,
    IntensiveWash: String,
    Jean: String,
    OnlySpin: String,
    OtherWashModes: [String],
    PreWash: String,
    Quick: String,
    Synthetic: String,
    Towel: String,
    Wool: String,
    BabyCare: String,
    "3-StepWash": String,
    Drain: String,
  },
  Options: [String],
  Rinse: String,
  Soak: String,
  StartStopPause: String,
  Wash: String,
  WashWindow: String,
  Technology: String,
  ChildLock: String,
  FaultDiagnosis: String,
  FuzzyLogic: String,
  AntiBacteriaTechnology: String,
  Display: String,
  Weight: String,
  HotColdWaterInlet: String,
  Knob: String,
  LidMaterial: String,
  MotorType: String,
  TouchControlButtons: String,
  TransparentWindow: String,
  WindowGlassType: String,
  TypeOfControl: String,
  Dimensions: {
    Height: String,
    Width: String,
    Depth: String,
  },
  DoorColor: String,
  DrumMaterial: String,
  DrumType: String,
  EndOfCycleIndicator: String,
  IndicatorsNotifications: String,
  Timer: String,
  EnergyRating: String,
  Frequency: String,
  Voltage: String,
  Spin: String,
  SpinWindow: String,
  MaxSpinSpeed: String,
  MaxTemperature: String,
  PackageContents: [String],
  NotCoveredInWarranty: String,
  Warranty: String,
  variants: [
    {
      store: String,
      price: String,
      store_link: String,
    },
  ],
  images: [String],
  ExpertScore: String,
});

export const WashingMachines = mongoose.model("washing_machines", WashingMachineSchema);
